# Needs to be refactored to use manifest.json in both containers, likely needs to have a single static assets volume
version: '3'

services:

  webapp:
    build:
      context: .
      dockerfile: ./docker/prod/app/Dockerfile
    container_name: webapp
    image: webapp:latest
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    container_name: nginx
    image: webapp-nginx
    ports:
      - "8888:80"
