"""route type

Revision ID: 5f2d38497768
Revises: 7089aedce1c1
Create Date: 2019-01-19 15:06:36.794514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2d38497768'
down_revision = '7089aedce1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'type')
    # ### end Alembic commands ###
